package com.example.backend.api.common;

public enum RequestCode {
    OK,
    CONVERSATION_NOT_FOUND,
    NULL_IMAGE,
    INVALID_IMAGE_FORMAT,
    IMAGE_NOT_FOUND,
    NULL_USERNAME,
    NULL_PASSWORD,
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    WRONG_PASSWORD,
    INVALID_ID,
    MESSAGE_TOO_LONG,
    INVALID_DATE,
    MESSAGE_NOT_FOUND,
    CONVERSATION_ALREADY_EXISTS,
    CANNOT_DELETE_IMAGE,
    EMPTY_MESSAGE,
    INVALID_MESSAGE_TYPE;
}
